import 'package:flutter/material.dart';

import '../model/number_generator.dart';

class NumberGeneratorView extends StatefulWidget {
  const NumberGeneratorView({Key? key}) : super(key: key);

  @override
  State<NumberGeneratorView> createState() => _NumberGeneratorViewState();
}

class _NumberGeneratorViewState extends State<NumberGeneratorView> {
  // save the random number generated by the function from another file
  int randomNumber1 = 0;
  int randomNumber2 = 0;
  // int greater = 0;

  late NumberGenerator numberGenerator;
  // late CheckGreater checkGreater;

  void tellMeNumber1() {
    numberGenerator = NumberGenerator();
    setState(() {
      randomNumber1 = numberGenerator.tellMeNumber1(randomNumber1);
    });
  }

  void tellMeNumber2() {
    numberGenerator = NumberGenerator();
    setState(() {
      randomNumber2 = numberGenerator.tellMeNumber2(randomNumber2);
    });
  }

  // void numberCheck() {
  //   checkGreater = CheckGreater();
  //   setState(() {
  //     greater = checkGreater.checkGreater(greater);
  //   });
  // }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Number generator game"),
        centerTitle: true,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(10),
          child: Column(
            children: [
              ElevatedButton(
                onPressed: () {
                  tellMeNumber1();
                  tellMeNumber2();
                },
                child: const Text('Generate Number'),
              ),
              const SizedBox(
                height: 8,
              ),
              Text(
                'First Random number is: $randomNumber1',
                style: const TextStyle(
                  fontSize: 20,
                  fontStyle: FontStyle.italic,
                  fontWeight: FontWeight.bold,
                  color: Colors.grey,
                ),
              ),
              const SizedBox(
                height: 8,
              ),
              Text(
                'second Random number is: $randomNumber2',
                style: const TextStyle(
                  fontSize: 20,
                  fontStyle: FontStyle.italic,
                  fontWeight: FontWeight.bold,
                  color: Colors.grey,
                ),
              ),
              const SizedBox(
                height: 8,
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ElevatedButton(
                    onPressed: () {
                      // do something
                      // numberCheck();
                    },
                    child: const Text('Button1'),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      // do something
                      // numberCheck();
                    },
                    child: const Text('Button2'),
                  ),
                ],
              ),
              const SizedBox(
                height: 8,
              ),
              const Text(
                'Correct : 0',
                style: TextStyle(
                  fontSize: 20,
                  fontStyle: FontStyle.italic,
                  fontWeight: FontWeight.bold,
                  color: Colors.grey,
                ),
              ),
              const SizedBox(
                height: 8,
              ),
              const Text(
                'InCorrect : 0',
                style: TextStyle(
                  fontSize: 20,
                  fontStyle: FontStyle.italic,
                  fontWeight: FontWeight.bold,
                  color: Colors.grey,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
